name: Build and Publish Python AI SDK to PyPI
on:
  push:

permissions:
  contents: write
  id-token: write

env:
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD_OVHAI }}
  PYPI_USERNAME: "__token__"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.pythonversion}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build Package
      run: |
        python ovhai/setup.py sdist 

    - name: Check worktree clean
      run: |
        git update-index -q --refresh
        if ! git diff-files --quiet; then
            >&2 echo "error: working tree is not clean, aborting!"
            git status
            git diff
            exit 1
        fi

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # tag=v1.8.10
      with:
          user: ${{ env.PYPI_USERNAME }}
          password: ${{ env.PYPI_PASSWORD }}
          packages-dir: dist
          skip-existing: true
          verbose: true
    strategy:
      fail-fast: true
      matrix:
        language:
          - python
        pythonversion:
          - "3.8"
